version: '3'

services:
  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - redis
      - mysql
    env_file: .env
  redis:
    image: redis:alpine
    env_file: .env
  mysql:
    image: mariadb:latest
    env_file: .env
    environment:
      MYSQL_DATABASE: accounting_app
